[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build:production"]

[start]
cmd = "NODE_ENV=production node apps/api/dist/index.js"
